--- #YAML:1.0
name:               Imager-File-PNG
version:            0.77
abstract:           PNG Image file support
author:
    - Tony Cook <tony@imager.perl.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    Imager:               0.77
build_requires:
    ExtUtils::MakeMaker:  0
    Imager:               0.77
    Test::More:           0.47
requires:
    Imager:  0.77
resources:
    homepage:  http://imager.perl.org/
    repository:
        type:  svn
        url:   http://imager.perl.org/svn/trunk/Imager-File-PNG
        web:   http://imager.perl.org/svnweb/public/browse/trunk/Imager-File-PNG
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
